---
extends:
  - eslint-config-shakacode
  - plugin:flowtype/recommended

plugins:
  - flowtype

env:
  jest: true

rules:
  no-unused-vars:
    - error
    - args: after-used

  arrow-body-style: off
  no-underscore-dangle: off

  react/sort-comp: off

  import/no-extraneous-dependencies:
    - error
    - devDependencies: true

  import/prefer-default-export: off

  flowtype/require-valid-file-annotation:
    - error
    - always

  flowtype/no-weak-types: error
  flowtype/no-dupe-keys: error
