---
extends:
  - "eslint-config-shakacode"
  - "plugin:flowtype/recommended"
  - "prettier"
  - "prettier/flowtype"
  - "prettier/react"

plugins:
  - "flowtype"
  - "prettier"

env:
  jest: true

rules:
  no-unused-vars:
    - "error"
    - args: "after-used"

  arrow-body-style: "off"
  no-underscore-dangle: "off"
  no-multi-assign: "off"

  prettier/prettier:
    - "error"
    - printWidth: 80
      tabWidth: 2
      trailingComma: "all"
      singleQuote: true

  react/sort-comp: "off"
  react/jsx-filename-extension:
    - "error"
    - extensions:
      - "js"

  import/no-extraneous-dependencies:
    - "error"
    - devDependencies: true

  import/prefer-default-export: "off"

  flowtype/require-valid-file-annotation:
    - "error"
    - "always"

  flowtype/no-weak-types: "error"
  flowtype/no-dupe-keys: "error"
