---
extends: eslint-config-shakacode

env:
  mocha: true

rules:
  no-multi-spaces:
    - 2
    - exceptions:
        ImportDeclaration: true
        ExportNamedDeclaration: true
        VariableDeclarator: true
        AssignmentExpression: true
  key-spacing:
    - 1
    - align: colon
      beforeColon: false
      afterColon: true
