// flow-typed signature: 2960a04918917c50058d99b37dae996f
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-function-name_v6.22.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-function-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-function-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-function-name/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-function-name/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-function-name/lib/index'>;
}
