// flow-typed signature: 1def7d29e7c9f77fc80504634c5e913c
// flow-typed version: <<STUB>>/lodash.set_v^4.3.2/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.set' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.set/index' {
  declare module.exports: $Exports<'lodash.set'>;
}
declare module 'lodash.set/index.js' {
  declare module.exports: $Exports<'lodash.set'>;
}
